inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.1

# メソッドの行数が多すぎる
MethodLength:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false
